name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.239.238.241
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/apply-bot
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
            echo "NEON_DATABASE_URL=${{ secrets.NEON_DATABASE_URL }}" >> .env
            npm install
            pm2 restart apply-bot || pm2 start index.js --name apply-bot
